### ISSUE TITLE
Error when animating a pie chart from state with fewer sections to one with more sections

### ISSUE THREAD

**Issue by ToyWalrus** [imaNNeoFighT/fl_chart#861]
The issue seems to be that when implicitly animating a PieChart from a state where it has `X` number of sections to a state where it has `Y` number of sections where `X < Y`, the following error gets thrown:
```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: Updated layout information required for RenderLimitedBox#fe2fd NEEDS-LAYOUT NEEDS-PAINT to calculate
flutter: semantics.
flutter: 'package:flutter/src/rendering/object.dart': package:flutter/…/rendering/object.dart:1
flutter: Failed assertion: line 2653 pos 12: '!_needsLayout'
```

The odd thing about this bug is that it only seems to happen once per app session, i.e. it's not reproducible again unless you do an app reset not just a hot reload.

```dart
class CrashExample extends StatefulWidget {
  @override
  _CrashExampleState createState() => _CrashExampleState();
}

class _CrashExampleState extends State<CrashExample> {
  List<double> get state0 => [1, 2, 3, 4];
  List<double> get state1 => [1, 2, 3, 4, 5];
  final colors = [Colors.red, Colors.blue, Colors.purple, Colors.green, Colors.grey];

  int currentState = 0;
  List<double> get stateVals => currentState == 0 ? state0 : state1;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Crash Example')),
      body: Center(
        child: Column(
          children: [
            ElevatedButton(onPressed: switchState, child: Text('Update')),
            SizedBox(height: 20),
            SizedBox(
              key: ValueKey('ChartContainer'),
              height: 150,
              child: PieChart(
                PieChartData(
                  sections: makeSections(),
                  centerSpaceColor: Colors.transparent,
                  borderData: FlBorderData(show: false),
                  centerSpaceRadius: double.infinity,
                  startDegreeOffset: -90,
                  sectionsSpace: 1,
                ),
                swapAnimationCurve: Curves.easeOut,
                swapAnimationDuration: Duration(milliseconds: 250),
              ),
            ),
          ],
        ),
      ),
    );
  }

  List<PieChartSectionData> makeSections() {
    final sections = <PieChartSectionData>[];
    for (final val in stateVals) {
      sections.add(PieChartSectionData(
        value: val,
        title: val.toString(),
        radius: 15,
        showTitle: false,
        color: colors[val.toInt() - 1],
      ));
    }

    return sections;
  }

  void switchState() {
    setState(() {
      currentState = (currentState + 1) % 2;
    });
  }
}
```

**Versions**
 - **Flutter** 2.2.3
 - **fl_chart** ^0.36.2

**Comment by imaNNeoFighT** [comment]
Hi. 
We have just fixed it in [0.45.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.45.0).
Please check it out!

**Comment by jingfeng-cheah** [comment]
Hi, unfortunately this issue still persists for me in 0.62.0. I had to set `swapAnimationDuration: Duration.zero` to prevent the error.

**Comment by imaNNeo** [comment]
> @imaNNeo Hi, unfortunately this issue still persists for me in 0.62.0. I had to set `swapAnimationDuration: Duration.zero` to prevent the error.

Can you provide a reproducible code? a `main.dart` file code
