### ISSUE TITLE
LineChart breaks with nullSpot values

### ISSUE THREAD

**Issue by AntonShinkaretsky** [imaNNeoFighT/fl_chart#912]
**Description**
1. LineChart simply throws an exception and fails to draw when its `List<FlSpot>` starts with a `FlSpot.nullSpot`:
```
The following assertion was thrown during paint():
'package:fl_chart/src/utils/utils.dart': Failed assertion: line 183 pos 12: 'input >= 1.0': is not true.
```
2. It also draws `belowBarData` fine only when there are no `FlSpot.nullSpot` values in the list. But as soon as there are, betweenBarsData is simply gone, without any exceptions.

**To Reproduce**
https://github.com/AntonShinkaretsky/fl_chart_bugs

**Screenshots**
![photo_2022-02-21_11-15-56](https://user-images.githubusercontent.com/23244380/154936447-2a1072a7-bb5d-48a0-9667-4795502b2b31.jpg)
![photo_2022-02-21_11-15-56 (2)](https://user-images.githubusercontent.com/23244380/154936451-19d17a67-e8ea-4177-b04d-c28ad7a8f58f.jpg)

**Versions**
 - [√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.22000.493], locale en-US)
 - fl_chart: ^0.45.0
 
 Thank you!

**Comment by imaNNeoFighT** [comment]
Hi.
I couldn't reproduce it with our samples.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/7009300/155386713-893f5d7c-e7e5-4ed5-b20b-b482e4ca35b8.png">

Also, your code is hard to reproduce. I cannot clone a repository on my machine per issue.
Please make a single `main.dart` file and give me here to run your reproducible code.

Thanks!

**Comment by AntonShinkaretsky** [comment]
Do you simply want it as plain text? There you have it:

```
import 'package:flutter/material.dart';
import 'package:fl_chart/fl_chart.dart';
import 'dart:math';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomeView(),
    );
  }
}

class HomeView extends StatelessWidget {
  const HomeView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text("FL Chart bugs (below are buttons):"),
              const SizedBox(height: 16),
              TextButton(
                onPressed: () {
                  Navigator.of(context).push(MaterialPageRoute(
                    builder: (context) => const FirstNullSpotBugView(),
                  ));
                },
                child: const Text("Line Chart: first nullSpot bug"),
              ),
              TextButton(
                onPressed: () {
                  Navigator.of(context).push(MaterialPageRoute(
                    builder: (context) => BetweenBarsDatBugView(),
                  ));
                },
                child: const Text("Line Chart: betweenBarsData bug"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class FirstNullSpotBugView extends StatelessWidget {
  const FirstNullSpotBugView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: ListView(
            children: [
              const Text("Works fine when all are values:"),
              const SizedBox(height: 4),
              LineChartView(
                lineBarsData: getOneLineChartBarData(
                  getMockedChartPoints(size: 5),
                ),
                betweenBarsData: const [],
              ),
              const SizedBox(height: 12),
              const Text("Works fine when nulls are in the end:"),
              const SizedBox(height: 4),
              LineChartView(
                lineBarsData: getOneLineChartBarData(
                  getMockedChartPoints(size: 5, nullIndexes: [4]),
                ),
                betweenBarsData: const [],
              ),
              const SizedBox(height: 12),
              const Text("Works fine when nulls are in the middle:"),
              const SizedBox(height: 4),
              LineChartView(
                lineBarsData: getOneLineChartBarData(
                  getMockedChartPoints(size: 5, nullIndexes: [2]),
                ),
                betweenBarsData: const [],
              ),
              const SizedBox(height: 12),
              const Text("BREAKS when the nullSpot is the first value:"),
              const SizedBox(height: 4),
              LineChartView(
                lineBarsData: getOneLineChartBarData(
                  getMockedChartPoints(size: 5, nullIndexes: [0]),
                ),
                betweenBarsData: const [],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class BetweenBarsDatBugView extends StatelessWidget {
  final betweenBarsData = [
    BetweenBarsData(
      fromIndex: 0,
      toIndex: 1,
      colors: [Colors.red.withOpacity(0.3)],
    )
  ];

  BetweenBarsDatBugView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: ListView(
            children: [
              const Text("Works fine when all are values:"),
              const SizedBox(height: 4),
              LineChartView(
                lineBarsData: getTwoLineChartBarData(
                  getMockedChartPoints(size: 5),
                  getMockedChartPoints(size: 5),
                ),
                betweenBarsData: betweenBarsData,
              ),
              const SizedBox(height: 12),
              const Text(
                "DOESN'T SHOW between bars data when nulls are in the end:",
              ),
              const SizedBox(height: 4),
              LineChartView(
                lineBarsData: getTwoLineChartBarData(
                  getMockedChartPoints(size: 5, nullIndexes: [4]),
                  getMockedChartPoints(size: 5, nullIndexes: [4]),
                ),
                betweenBarsData: betweenBarsData,
              ),
              const SizedBox(height: 12),
              const Text(
                "DOESN'T SHOW between bars data when nulls are in the middle:",
              ),
              const SizedBox(height: 4),
              LineChartView(
                lineBarsData: getTwoLineChartBarData(
                  getMockedChartPoints(size: 5, nullIndexes: [2]),
                  getMockedChartPoints(size: 5, nullIndexes: [2]),
                ),
                betweenBarsData: betweenBarsData,
              ),
              const SizedBox(height: 12),
              const Text("BREAKS when the nullSpot is the first value:"),
              const SizedBox(height: 4),
              LineChartView(
                lineBarsData: getTwoLineChartBarData(
                  getMockedChartPoints(size: 5, nullIndexes: [0]),
                  getMockedChartPoints(size: 5, nullIndexes: [0]),
                ),
                betweenBarsData: betweenBarsData,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class LineChartView extends StatelessWidget {
  final List<LineChartBarData> lineBarsData;
  final List<BetweenBarsData> betweenBarsData;

  const LineChartView({
    Key? key,
    required this.lineBarsData,
    required this.betweenBarsData,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 40,
      child: Container(
        decoration: BoxDecoration(
          border: Border(
            top: BorderSide(color: Colors.grey[300]!),
            bottom: BorderSide(color: Colors.grey[300]!),
            right: BorderSide(color: Colors.grey[300]!),
            left: BorderSide(color: Colors.grey[300]!),
          ),
        ),
        child: LineChart(
          LineChartData(
            minY: 0,
            maxX: 4,
            lineBarsData: lineBarsData,
            betweenBarsData: betweenBarsData,
            titlesData: FlTitlesData(
              leftTitles: SideTitles(showTitles: false),
              topTitles: SideTitles(showTitles: false),
              bottomTitles: SideTitles(showTitles: false),
              rightTitles: SideTitles(showTitles: false),
            ),
            gridData: FlGridData(show: false),
            borderData: FlBorderData(show: false),
          ),
        ),
      ),
    );
  }
}

List<FlSpot> getMockedChartPoints({
  required int size,
  int min = 0,
  int max = 30,
  List<int> nullIndexes = const [],
}) {
  var rng = Random();
  List<FlSpot> result = [];
  int index = 0;
  while (index < size) {
    if (nullIndexes.contains(index)) {
      result.add(FlSpot.nullSpot);
    } else {
      result.add(
        FlSpot(
          index.toDouble(),
          min + rng.nextInt(max - min).toDouble(),
        ),
      );
    }
    index++;
  }
  return result;
}

List<LineChartBarData> getOneLineChartBarData(List<FlSpot> flSpotsList) {
  return [
    LineChartBarData(
      showingIndicators: [],
      spots: flSpotsList,
      isCurved: true,
      barWidth: 2,
      belowBarData: BarAreaData(
        show: true,
        colors: [
          Colors.blue[50]!,
        ],
      ),
      dotData: FlDotData(show: false),
      colors: [Colors.blue[200]!],
    )
  ];
}

List<LineChartBarData> getTwoLineChartBarData(
    List<FlSpot> flSpotsList,
    List<FlSpot> secondFlSpotsList,
    ) {
  return [
    LineChartBarData(
      showingIndicators: [],
      spots: flSpotsList,
      isCurved: true,
      barWidth: 2,
      belowBarData: BarAreaData(
        show: false,
      ),
      dotData: FlDotData(show: false),
      colors: [Colors.blue[200]!],
    ),
    LineChartBarData(
      showingIndicators: [],
      spots: secondFlSpotsList,
      isCurved: true,
      barWidth: 2,
      belowBarData: BarAreaData(
        show: false,
      ),
      dotData: FlDotData(show: false),
      colors: [Colors.red[200]!],
    ),
  ];
}

```

**Comment by imaNNeoFighT** [comment]
Okay, I found the bug now.

**Comment by AntonShinkaretsky** [comment]
Awesome, thank you for such a quick reaction! :)

**Comment by imaNNeoFighT** [comment]
That's the power of reproducible code :)
I just fixed it in #916.

**Comment by AntonShinkaretsky** [comment]
I'll check it out in a sec. 
Do you think it will fix both nullSpot-s in the beginning, and betweenBarsData?

**Comment by imaNNeoFighT** [comment]
It will be landed on the stable version soon.

**Comment by imaNNeoFighT** [comment]
Yes, It will fix both of them.

**Comment by AntonShinkaretsky** [comment]
Awesome, thank you!

**Comment by imaNNeoFighT** [comment]
Landed on the `dev` branch. (check [here](https://stackoverflow.com/a/54023220/3543738) to get the `dev` version)

**Comment by imaNNeoFighT** [comment]
Fixed in [0.45.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.45.1).
Thanks for reporting!

**Comment by AntonShinkaretsky** [comment]
@imaNNeoFighT as you can see with the very same example, it does fix "first nullSpot" behavior, but it doesn't fix `betweenBarsData`:
![photo_2022-03-04_09-46-14 (2)](https://user-images.githubusercontent.com/23244380/156730553-ac5fab2e-31b4-41db-a8dd-d31d82f1a519.jpg)
![photo_2022-03-04_09-46-14](https://user-images.githubusercontent.com/23244380/156730555-826763ea-0b65-4e55-8b8f-31c104d8d331.jpg)

**Comment by AntonShinkaretsky** [comment]
Do you want me to create a separate issue for that?

**Comment by imaNNeoFighT** [comment]
No need to create a new issue.
I'm trying to fix it. (I didn't know there is a problem with between bars)

**Comment by imaNNeoFighT** [comment]
It has just been fixed in the `dev` branch.
If you can test it, please try it.

**Comment by imaNNeoFighT** [comment]
Check it out in [0.46.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.46.0)

**Comment by AntonShinkaretsky** [comment]
Sorry, didn't have a chance to check it out before.
It does work, thank you!

In the future, you could also filter out values that don't have pairs instead of throwing an exception btw. Not something I personally need right now, but I think would be nice for the library in general :)
