### ISSUE TITLE
Doesn't work on web

### ISSUE THREAD

**Issue by andermoran** [imaNNeoFighT/fl_chart#95]
It does not render correctly on the web. I know the web is only in technical preview so I didn't expect it to work but it would be nice if it did.

**Render on mobile (good)**
![image](https://user-images.githubusercontent.com/15237301/67772023-5cda7500-fa27-11e9-826f-ce361cc106f9.png)

**Render on web (bad)**
![Screen Shot 2019-10-28 at 11 01 46 AM](https://user-images.githubusercontent.com/15237301/67695108-900efc80-f972-11e9-8a66-1e7ef82a3bf9.png)

**Comment by imaNNeoFighT** [comment]
Hi dude, great to see it on the web,
We are not going to focus on the web,
but may I ask you what is your problem with that (the second image)?

**Comment by andermoran** [comment]
Yes, I get that the web isn't a priority. I was just letting you know how it works on the web. The data for the charts is the exact same. It paints the lines correctly on the top graph but on the bottom graph the lines go crazy

**Comment by imaNNeoFighT** [comment]
Got it,
Thanks!

**Comment by andymillernz** [comment]
There is a bug in the _Path.from_ function in the web engine - it effectively creates a pointer to the path instead of a deep copy.

Fix is to change the 2 occurrences of _Path.from_ to '_shift_' in _line_chart_painter.dart_ (I'm sure there are other/better fixes, this happens to be the one that works for me).

```
// final belowBarPath = Path.from(barPath);
    final belowBarPath = barPath.shift(Offset(0, 0));
...
```

**Comment by ChenYunerer** [comment]
andymillernz`s method is worked

**Comment by imaNNeoFighT** [comment]
Did you test in the new flutter veraion?

**Comment by ChenYunerer** [comment]
my flutter version is Flutter 1.10.16 • channel master

**Comment by imaNNeoFighT** [comment]
May I ask you to check it in 1.12?

**Comment by imaNNeoFighT** [comment]
May I ask you to check it in 0.12?

**Comment by andymillernz** [comment]
> May I ask you to check it in 0.12?

I've created a [bug report](https://github.com/flutter/flutter/issues/46813) with the flutter team re: the issue with Path.from...

**Comment by imaNNeoFighT** [comment]
Well done,
Thanks!

**Comment by Ferdzzzzzzzz** [comment]
@imaNNeoFighT my proposed workaround for web is very simple:
`final belowBarPath = kIsWeb ? barPath.shift(const Offset(0, 0)) : Path.from(barPath);`

Not sure how to test packages locally in my application, any advice on how to do that? :)

**Comment by abc873693** [comment]
It work in flutter` v1.13.9-pre.59`. fl_chart `0.6.3`

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v1.13.9-pre.59, on Mac OS X 10.15.2 19C57, locale zh-Hant-TW)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.5)
> [✓] VS Code (version 1.41.1)
> [✓] Connected device (3 available)

![](https://i.imgur.com/1ijCv5B.png)

**Comment by andymillernz** [comment]
For best results (at this point in time) you need to run in release mode with SKIA enabled..  

I assume (hope?) that this will become the default at some point..

`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true --release`

**Comment by Dimarv135** [comment]
For me only Pie chart doesn't show up on web.Same code/data that runs fine on mobile doesn't show anything on web. My app has also line chart, bar chart, stacked- bar chart which all work fine on Web.
Release mode didn't help. SKIA fixes the problem with the pie chart but the rest of my app doesn't support it.

**Comment by Mecil9** [comment]
> For me only Pie chart doesn't show up on web.Same code/data that runs fine on mobile doesn't show anything on web. My app has also line chart, bar chart, stacked- bar chart which all work fine on Web.
> Release mode didn't help. SKIA fixes the problem with the pie chart but the rest of my app doesn't support it.

me to0..........
Pie chart can't display the circle draw....only show the Indicator's data....

did u fix it?

**Comment by imaNNeoFighT** [comment]
I think it has been fixed (at least I see it is fixed in beta channel)
Am I correct?

**Comment by darrillaga** [comment]
Line chart still not working in web, I tried switch Path.from with shift and didn't work

**Comment by imaNNeoFighT** [comment]
Okay tnx

**Comment by darrillaga** [comment]
Sorry for the message with lack of content, the following are iOS vs Chrome.
If I enable SKIA I just get only the solid lines. Let me know if I can help you with something to get this fixed.

iOS:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/970228/81026566-ec3a6800-8e50-11ea-9ecf-2e91931e8028.png">

Chrome:
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/970228/81026510-c1501400-8e50-11ea-86d0-d53382e1f293.png">

**Comment by andymillernz** [comment]
There are still some limitations in the 'painting/blend/path' functions for the web flutter implementation.

In this case the issue relates to using a dash line.. And it looks reasonably correct if you comment out the dashArray in _line_chart_sample8.dart_ 

```           FlSpot(6.8, 5),
            FlSpot(8, 1),
            FlSpot(9.5, 2),
            FlSpot(11, 4),
          ],
          // dashArray: [2, 4],
          isCurved: true,
```

If you want the pie chart to work you need to patch _lib/src/pie_chart/pie_chart_painter.dart_ and remove or change the blendMode in sectionsSpaceClearPaint - this does impact the pie chart functionality. however at least gets things to work..
```
sectionsSpaceClearPaint = Paint()
      ..style = PaintingStyle.fill
      ..color = const Color(0x000000000)
      // ..blendMode = BlendMode.srcOut;
      ..blendMode = BlendMode.color;
```

**Comment by darrillaga** [comment]
it worked without dash array, great thanks!

**Comment by imaNNeoFighT** [comment]
I think it doesn't exist anymore.
Can somebody check it and let me know?

**Comment by OlegNovosad** [comment]
@imaNNeoFighT checked and was not able to reproduce it. We can close it I think.

**Comment by imaNNeoFighT** [comment]
Congrats! :))

**Comment by santro93** [comment]
For deploying web package what should i use?

**Comment by OlegNovosad** [comment]
> For deploying web package what should i use?

What do you mean? This package supports web.
